FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md ./
COPY src ./src

RUN uv sync --frozen --no-dev

COPY pipelines ./pipelines
COPY monitoring ./monitoring
COPY config ./config
COPY serving ./serving
COPY main.py .

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/src:/app"

CMD ["prefect", "worker", "start", "--pool", "open-food-mlops"]
