global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "open_food_mlops_serving"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]