# config/logging.yaml
version: 1
disable_existing_loggers: false

formatters:
  simple: 
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s [%(filename)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO 
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/open_food_mlops.log 
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf8

root: 
  level: INFO
  handlers: [console, file]